# Base Image
FROM openjdk:8u332-slim-bullseye
COPY --from=python:3.8 / /
# COPY app
COPY ./feast_api /app

# pip install requirements
RUN pip install --upgrade pip
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
